spring:
  application:
    name: aligo-flow-demo
    #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/aligo-flow
    username: root
    password: ymh96122
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8888


aligo:
  flow:
    #数据源类型
    schema: xsd
  global:
    #应用id
    appId: AligoFlowDemoApp
    #指定事务模板
#    transactionTemplate: flowTransactionTemplate



